# Generated by Django 4.0 on 2022-06-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_about_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
